# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Boring"
license = "Apache 2.0"
licenselink = "https://github.com/mesaugat/hugo-boring/blob/master/LICENSE"
description = "Boring is an opnionated and minimal Hugo theme."
homepage = "https://github.com/mesaugat/hugo-boring/"
tags = ["Blog", "Responsive", "Minimal"]
features = ["Blog", "Responsive"]
min_version = "0.74.0"
authors = [
  { name = "C. Wang", homepage = "https://www.wangchucheng.com/" },
  { name = "R. Ma", homepage = "https://ruiqima.com/" },
  { name = "Saugat Acharya", homepage = "https://theboring.dev/" },
]
