name: Hugo Boring Build Assets

on:
  push:
    branches:
      - master
    paths:
      - assets/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install NPM Packages
        run: |
          npm install
          sudo npm install -g postcss postcss-cli

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3

      - name: Build and Copy Resources
        working-directory: exampleSite
        run: |
          hugo
          cp -r resources ../

      - name: Commit Resources
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: New build
